### ISSUE TITLE
1.14d

### ISSUE THREAD

**Issue by Colourcloud** [BinaryNinjas/Rogue-of-Diablo-v2#1]
Has this been updated to 1.14d? I know its the source code, just wasn't sure what needs to be updated

Thanks for sharing 👍

**Comment by BinaryNinjas** [comment]
As long as the protocol hasn't changed since the version byte of 0x0D, everything should still work.  Just update the hashes and verbyte and it should still work.  

If it doesn't please post the issues here.

**Comment by Colourcloud** [comment]
I added the new hashes for 1.14

Also changed the verbyte to 0E on the bot. But it still says  BNCS(0) Old Game Version
